stages:
  - build
  - deploy

build_containder:
  stage: build
  services:
  - docker:dind
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS https://index.docker.io/v1
    - docker build -t ecohealthalliance/ffox-server:latest .

push_image:
  stage: deploy
  services:
  - docker:dind
  script:
  - docker push ecohealthalliance/ffox-server:latest

