image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - build
  - deploy

build_containder:
  stage: build
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS https://index.docker.io/v1
    - docker build -t ecohealthalliance/ffox-server:latest .

push_image:
  stage: deploy
  script:
    - docker push ecohealthalliance/ffox-server:latest

