image: docker:stable
services:
  - docker:dind

stages:
  - build

build_containder:
  stage: build
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS index.docker.io
    - docker build -t index.docker.io/ecohealthalliance/ffox-server:latest .
    - docker push index.docker.io/ecohealthalliance/ffox-server:latest



